$VersionControl = 'git'
$VersionControlRepos = @(
	"git@github.com:pip-webui2/pip-webui2-layouts.git"
	"git@github.com:pip-webui2/pip-webui2-nav.git"
	"git@github.com:pip-webui2/pip-webui2-behaviors.git"
	"git@github.com:pip-webui2/pip-webui2-themes.git"
	"git@github.com:pip-webui2/pip-webui2-controls.git"
	"git@github.com:pip-webui2/pip-webui2-buttons.git"
	"git@github.com:pip-webui2/pip-webui2-cache.git"
	"git@github.com:pip-webui2/pip-webui2-landing.git"
	"git@github.com:pip-webui2/pip-webui2-locations.git"
	"git@github.com:pip-webui2/pip-webui2-pictures.git"
	"git@github.com:pip-webui2/pip-webui2-documents.git"
	"git@github.com:pip-webui2/pip-webui2-files.git"
	"git@github.com:pip-webui2/pip-webui2-dates.git"
	"git@github.com:pip-webui2/pip-webui2-composite.git"
	"git@github.com:pip-webui2/pip-webui2-dialogs.git"
	"git@github.com:pip-webui2/pip-webui2-errors.git"
	"git@github.com:pip-webui2/pip-webui2-entry.git"
	"git@github.com:pip-webui2/pip-webui2-shell.git"
)
